# Generated by Django 2.0.1 on 2018-06-09 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='id',
        ),
        migrations.AddField(
            model_name='person',
            name='email_field',
            field=models.EmailField(default='et3fx@virginia.edu', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='person_id',
            field=models.CharField(default='hi', max_length=50, primary_key=True, serialize=False, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
