# Generated by Django 2.0.1 on 2018-06-10 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20180609_1700'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='email_field',
            new_name='email',
        ),
    ]
