# Generated by Django 2.0.1 on 2018-06-16 16:29

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20180616_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='summary',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
