# Generated by Django 2.0.1 on 2018-06-16 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_auto_20180616_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='need_added_to_email',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='person',
            name='need_removed_from_email',
            field=models.BooleanField(default=False),
        ),
    ]
