# Generated by Django 2.0.1 on 2018-06-16 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_auto_20180616_1749'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='summary',
        ),
        migrations.AddField(
            model_name='person',
            name='degree_program',
            field=models.CharField(blank=True, choices=[('BS', "Bachelor's"), ('MS', "Master's"), ('PHD', 'Doctorate'), ('O', 'Other')], default='BS', max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='graduation_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='major',
            field=models.CharField(blank=True, default='Undecided', max_length=50, null=True),
        ),
    ]
