# Generated by Django 2.0.1 on 2018-06-19 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_project_body'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['end_date', 'start_date']},
        ),
    ]
